### ISSUE TITLE
What is the status of this test?

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-swecommon20#1]
Hi @epicureanism, what is the status of this test? Is it ready for beta and what are the conformance classes documented in the test?

**Comment by epicureanism** [comment]
There are 105 requirements in 17 conformance classes, and some requirements are not easy to implement. Instead of marking the whole conformance class are tested, we prefer documented them in more detail way to show the status of each requirement. 
For those interested in what requirements are tested, please reference the following link:
https://github.com/opengeospatial/ets-swecommon20/blob/master/src/site/markdown/index.md

As the time of responding this issue, we've implemented most requirements in A.1, A.2.
